=== andreivasiliu/project-rawi/branches/svg-status-graph/W-Prototype/src/resources/TransformationModel.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/TransformationModel" elementFormDefault="qualified" xmlns:tm="http://www.example.org/TransformationModel">

    <element name="transformationModel"
    	type="tm:transformationModelType">
    </element>
    
    <complexType name="transformationGraphType">
        <sequence>
        	<choice minOccurs="0" maxOccurs="unbounded"><element name="packNode" type="tm:packNodeType">
        	</element><element name="packTransformerNode" type="tm:packTransformerType">
        	</element></choice>
        </sequence>
    </complexType>

    <complexType name="packNodeType">
    	<complexContent>
    		<extension base="tm:nodeType">
    			<sequence>
    				<choice>
    					<element name="pattern" type="tm:patternType"></element>
    					<element name="patternList"
    						type="tm:patternListType">
    					</element>
    				</choice>
    			</sequence>
    			<attribute name="isSplitter" type="boolean" use="optional"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="packTransformerType">
    	<complexContent>
    		<extension base="tm:nodeType">
    			<sequence>
    				<element name="command" type="tm:commandType"></element>

    			</sequence>
    			<attribute name="isJoiner" type="boolean" use="optional"></attribute>
    		</extension>
    	</complexContent>
    </complexType>

    <complexType name="nodeType" abstract="true">
    	<sequence>
    		<element name="input" type="tm:linkType" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    		<element name="output" type="tm:linkType" minOccurs="0"
    			maxOccurs="unbounded">
    		</element>
    	</sequence>
    	<attribute name="id" use="required" type="tm:idType">
    	</attribute>
    	<attribute name="name" type="tm:nameType" use="optional"></attribute>
    	<attribute name="x" type="int" use="optional"></attribute>
    	<attribute name="y" type="int" use="optional"></attribute>
    </complexType>

    <simpleType name="idType">
    	<annotation>
    		<documentation>
    			A node ID is a positive number. It may not be 0.
    		</documentation>
    	</annotation>
    	<restriction base="int">
    		<minInclusive value="1"></minInclusive>
    	</restriction>
    </simpleType>


    <complexType name="linkType">
    	<attribute name="node" type="tm:idType"></attribute>
    </complexType>

    <complexType name="transformationModelType">
        <sequence>
            <element name="globalParameters"
            	type="tm:globalParametersType" minOccurs="0" maxOccurs="1">
            </element>
            <element name="transformationGraph"
        		type="tm:transformationGraphType" minOccurs="1"
        		maxOccurs="1">
        	</element>

        </sequence>
    </complexType>

    <simpleType name="nameType">
    	<restriction base="string">
    		<minLength value="1"></minLength>
    	</restriction>
    </simpleType>

    <complexType name="patternType">
    	<attribute name="name" use="optional">
    		<simpleType>
    			<restriction base="string">
    				<pattern value="[a-zA-Z][a-zA-Z0-9-_]*"></pattern>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<anyAttribute processContents="skip"></anyAttribute>
    </complexType>

    <complexType name="patternListType">
    	<sequence>
    		<element name="patternItem" type="tm:patternType" minOccurs="1" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="commandType">
    	<anyAttribute processContents="skip"></anyAttribute>
    </complexType>

    <complexType name="globalParametersType">
    	<sequence>
    		<element name="parameter" type="tm:parameterType"></element>
    	</sequence>
    </complexType>

    <complexType name="parameterType">
    	<attribute name="name" use="required">
    		<simpleType>
    			<restriction base="string">
    				<pattern value="[a-zA-Z][a-zA-Z0-9-_]*"></pattern>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="default" type="string"></attribute>
    </complexType>


</schema>

=== andreivasiliu/project-rawi/WI-Prototype-GUI/src/rawi/resources/giant-model.xml
<?xml version="1.0" encoding="UTF-8"?>
<transformationModel xmlns="http://www.example.org/TransformationModel"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://www.example.org/TransformationModel TransformationModel.xsd">
    <transformationGraph>
	    <packNode id="1" name="Pack1" isSplitter="true" x="150" y="50">
	    	<output node="2" />
	    </packNode>
	    <packTransformerNode id="2" name="transformer1" x="150" y="125">
	    	<input node="1" />
	    	<output node="3" />
	    </packTransformerNode>
	    <packNode id="3" name="Pack2" x="150" y="200">
	    	<input node="2" />
	    </packNode>
    </transformationGraph>
</transformationModel>

=== andreivasiliu/project-rawi/W-Prototype/src/resources/RaytracerModel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- The <pattern/> and <command/> elements will eventually look different. -->

<transformationModel
   xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns='http://www.example.org/TransformationModel'
   xsi:schemaLocation='http://www.example.org/TransformationModel TransformationModel.xsd'>
    <globalParameters>
        <parameter name="nr" default="10" />
    </globalParameters>

    <transformationGraph>
        <packNode id="1" name="SceneFile" x="280" y="40">
            <output node="2" />
            <output node="4" />
            <pattern name="scene" regex="cod.cad" />
        </packNode>
        <packTransformerNode id="2" name="Splitter" x="180" y="120">
            <input node="1" />
            <output node="3" />
            <command exec="Splitter.exe 4 500 500" />
        </packTransformerNode>
        <packNode id="3" name="SectionFile" x="180" y="210" isSplitter="true">
            <input node="2" />
            <output node="4" />
            <output node="6" />
            <pattern name="section" regex=".*\.rd" />
        </packNode>
        <packTransformerNode id="4" name="Renderer" x="280" y="290">
            <input node="1" />
            <input node="3" />
            <output node="5" />
            <command exec="TinyRaytracer.exe $SceneFile $SectionFile" />
        </packTransformerNode>
        <packNode id="5" name="RenderedSection" x="280" y="380">
            <input node="4" />
            <output node="6" />
            <pattern regex=".*\.png" />
        </packNode>
        <packTransformerNode id="6" name="Joiner" x="180" y="450" isJoiner="true">
            <input node="3" />
            <input node="5" />
            <output node="7" />
            <command exec="Joiner.exe $SectionFile" />
        </packTransformerNode>
        <packNode id="7" name="RenderedScene" x="180" y="560">
            <input node="6" />
            <pattern regex=".*\.png" />
        </packNode>
        <packNode id="8" name="Splitter.exe" x="80" y="50">
            <output node="2" />
        </packNode>
        <packNode id="9" name="TinyRaytracer.exe" x="380" y="100"
                  allowsMultipleFiles="true">
            <output node="4" />
        </packNode>
        <packNode id="10" name="Joiner.exe" x="80" y="390">
            <output node="6" />
        </packNode>
<!--        <packNode id="11" name="Version12.0.cgt" x="380" y="175">
            <output node="4" />
        </packNode>
        <packNode id="12" name="GoldParser.dll" x="380" y="250">
            <output node="4" />
        </packNode> -->
    </transformationGraph>
</transformationModel>
